customize:
  property: qincy2
server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /provider1
spring:
  profiles:
    active: deve
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  application:
    name: provider1